name: Web E2E Tests

on:
    workflow_dispatch:

jobs:
    e2e-tests:

        runs-on: ubuntu-latest

        steps:

            #clone do projeto
            - uses: actions/checkout@v4

            #conferir versão do node instalada
            - name: Node version
              run: node --version

            - name: Instalando depêndencias
              run: npm install

            - name: Instalando Cypress
              run: npx cypress install

            - name: Executando os testes web
              run: npm run test-web

            - name: Executando os testes de API
              run: npm run test-api

            - uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                name: relatorios
                path: |
                  cypress/reports
                  cypress/screenshots
                  cypress/videos
